sudo: required

language: c

compiler:
- gcc
- clang

services:
- docker

arch:
  repos:
  - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
  - reflector
  - neofetch
  script:
  - sudo neofetch
  - reflector --verbose -l 20 --sort rate -p https
  - echo $CC
  - touch test_file
  - "sudo sh update_motd.sh"

script:
# build new image
- docker build --rm=true -t mikkeloscar/arch-travis:latest .
# run arch-travis to test new image
- bash ./arch-travis.sh
- ls -l